### ISSUE TITLE
Tool of Lore

### ISSUE THREAD

**Issue by petrosh** [petrosh/diarissues#19]
![ToL](https://cloud.githubusercontent.com/assets/4997583/24510101/85f12e26-1568-11e7-8246-87dee77e166a.png)

# Tool of Lore

- [Map](https://github.com/petrosh/diarissues/issues/19#issuecomment-283403316)
- [Generators & solvers](https://github.com/petrosh/diarissues/issues/19#issuecomment-283403013)
- [Fonts](https://github.com/petrosh/diarissues/issues/19#issuecomment-283421189)
- [Miscellanea](https://github.com/petrosh/diarissues/issues/19#issuecomment-283403414)
- [Ideas](https://github.com/petrosh/diarissues/issues/19#issuecomment-331736129)
- [Dawn_of_Worlds](https://github.com/petrosh/diarissues/issues/19#issuecomment-331936518)
- [Traveller](https://github.com/petrosh/diarissues/issues/19#issuecomment-331939124)
- [Schemas](https://github.com/petrosh/diarissues/issues/19#issuecomment-365672093)
- [SVGs](https://github.com/petrosh/diarissues/issues/19#issuecomment-381333153)
- [trasparente](https://github.com/petrosh/diarissues/issues/19#issuecomment-601364012)
  - [lucciola](https://github.com/petrosh/diarissues/issues/19#issuecomment-701411182)
- [Fall of civilizations](https://github.com/petrosh/diarissues/issues/19#issuecomment-864569244)
- [Snowpiercer](https://github.com/petrosh/diarissues/issues/19#issuecomment-924103597)
- [GPT](https://github.com/petrosh/diarissues/issues/19#issuecomment-1345654903)

---

- [Evolution gist](https://gist.github.com/petrosh/cac8dcdf8338bcee217a)
- [Worlds (issue #20 )](https://github.com/petrosh/diarissues/issues/20)
- [libraries.io](https://libraries.io/github/tool-of-lore)

---

Write in markdown and share static site, update, work with collaborators, no hassle.

- The Homebrewery: [Homebrew D&D made easy](http://homebrewery.naturalcrit.com/)
- Repository: https://github.com/tool-of-lore/legendary-adventure

## Links

- [JPL - Solar system simulator](http://space.jpl.nasa.gov/)
- [Explain like I’m five: Jekyll collections](http://ben.balter.com/2015/02/20/jekyll-collections/)
- [How GitHub uses GitHub to document GitHub](https://github.com/blog/1939-how-github-uses-github-to-document-github)

## Why

- [More people are playing D&D online than ever before](https://www.polygon.com/2017/7/20/16005982/dungeons-and-dragons-online-roll20-data)
- [Version Control for Microsoft Word](https://www.simuldocs.com/blog/ben-morris/version-control-for-microsoft-word)
  > long lived document with other people: lawyers, journalists, academics, authors, etc..
- [tiddlywiki HelloThere](http://tiddlywiki.com/)
  > Welcome to TiddlyWiki, a unique non-linear notebook for capturing, organising and sharing complex information. Use it to keep your to-do list, to plan an essay or novel, or to organise your wedding.

## Jekyll

**Flow**

1. Fork
2. Activate gh-pages
3. Commit

**Structure**

- Themes (css)
- Layouts (columns etc)
- Snippets (specific markup)

**Functions**

- Pages (rules)
- Posts (date on filename, lore, category and tags)
- Collections (bestiary, map, items, locations)
- Data (actors: **jsoneditor** can be involved for editing: pre-fill files)

On GitHub

- Comments
- Issues
- Releases

**Comment by petrosh** [comment]
# Generators & solvers

- [`generators` Gist](https://gist.github.com/petrosh/6fc2fde4b3f91bd8ace59364174d3064)
- http://anydice.com/program/db2b

### Gods

- [random-god-generator-or-who-dat-god](http://fistsofcinderandstone.blogspot.it/2017/06/random-god-generator-or-who-dat-god.html)

`_generators`

- `city`
  - `area`  
- `country`
  - `hex`

### Names

```
_generators/names/ships.md
_generators/names/characters.md
```

**`ships.md`**

```liquid
---
names: ["Nauvoo","Heart of Gold","Millennium Falcon"]
---
```

---

- [1d100 Actually Medieval Professions](https://coinsandscrolls.blogspot.it/2017/06/osr-1d100-actually-medieval-professions.html)

**Comment by petrosh** [comment]
## Map

**Hexes**

- Hexes [Hexagonal Grids](http://www.redblobgames.com/grids/hexagons/)

```yml
- type: elevation
- points:
  - [x1, y1, value1]
  - [x2, y2, value2]
- points: [[x1, y1, value1], [x2, y2, value2]]
```

**Weather**

- [Launch Mission Execution Forecast](https://www.patrick.af.mil/Portals/14/L-3%20Forecast%203%20Aug%20Launch.pdf)

**Editor**

- Draw, modify geographic **layers**
  - Elevation
  - Average precipitation
  - Average temperature
    - Biome
  - Regions (Politic)
  - Mana
  - Crimes
- Draw, modify **features**
  - Roads
  - Rivers
  - Locations

**bl.ocks**

- [Drag + Zoom](https://bl.ocks.org/mbostock/6123708)
- [Hexagon Mesh](https://bl.ocks.org/mbostock/5249328)
- [Quadtree](https://gist.github.com/petrosh/e5bd28e49589e08bedf2b2d2d67b7f52)
  ```css
  .node { shape-rendering: crispEdges; }
  ```

**System**

- Pointer like tribals, coordinates
- maps have parent maps and so on (continent, region, village, castle, room)
- [LotR Timeline](http://lotrproject.com/timeline/#zoom=2&lat=-1485&lon=1500&layers=B)

**Openlayers.js**

- [Icon colors](http://openlayers.org/en/latest/examples/icon-color.html?q=point)
- [Mouse position](http://openlayers.org/en/latest/examples/mouse-position.html?q=position)
- [Static image](http://openlayers.org/en/latest/examples/static-image.html?q=map+image)
- [Snap interaction](http://openlayers.org/en/latest/examples/snap.html?q=draw)
- [Overlay](http://openlayers.org/en/latest/examples/overlay.html)
- [Icon Symbolizer](http://openlayers.org/en/latest/examples/icon.html?q=mark)
- Book: [](http://openlayersbook.github.io/ch08-interacting-with-your-map/example-05.html)

**Comment by petrosh** [comment]
## Miscellanea

**Genres**

- [a_guide_to_worldbuilding_genres](https://www.reddit.com/r/worldbuilding/comments/6j4v6a/a_guide_to_worldbuilding_genres/)

**Worldbuilding Monthly**

- [#1 April 2017](https://drive.google.com/file/d/0BzL70KVdmhBjN2RsSnJUWE1aaGc/view)
- [#2 May 2017](https://drive.google.com/file/d/0B7XPSArWbOFFSHgtNDhxMEVWVDQ/view)
- [#3 Jun 2017](https://drive.google.com/file/d/0B7XPSArWbOFFMXlBbjdSbERVMkk/view)
- [#4 July 2017](https://drive.google.com/file/d/0BzL70KVdmhBjZVZnZ2xUVzMxb0k/view)
- [#5 Aug 2017](https://drive.google.com/file/d/0B7XPSArWbOFFcmZKUHViRUFjZWc/view)

**[Postantera](https://www.reddit.com/r/worldbuilding/comments/5v2wuo/new_world_of_postantera_upon_arrival_of_humans/)**

**To do**

- Date to calendar and calendar to date conversions (need javascript)
- Actors with searchable genealogy
- [Ask Spock](http://petrosh.github.io/ask-spock/) bot

**To check**

- When source repo is updated, can you pull request saving posts?

## Rock, paper, scissor

S:-1
R:0
P:1

`diff`
S-R:-1 L
S-P:-2 W
P-S:+2 L
P-R:+1 W
R-P:-1 L
R-S:+1 W

`(diff=+1 || diff=-2) then win`
`(diff=-1 || diff=2) then loose`

`-2 -1 0 +1 +2`
`WW  LL T  WW  LL`

# Hexes schemas

- [7 Hexes of Awesome](https://fuckyeahdnd.tumblr.com/post/152204495892/7-hexes-of-awesome)
- [Six Dimensional Weather](http://whatwouldconando.blogspot.it/2017/04/five-dimensional-weather.html)
- [Medieval Stalemate Simulator](https://coinsandscrolls.blogspot.it/2017/05/osr-medieval-stalemate-simulator-or-six.html)

## Icons

- https://github.com/nagoshiashumari/Rpg-Awesome
- [How We Created RPG Awesome](https://hackernoon.com/how-we-created-rpg-awesome-c33198cf4a84)

**Comment by petrosh** [comment]
## Fonts

**[Gurps lite](http://www.sjgames.com/gurps/lite/3e/gurpslite.pdf)**

- Garamond: `font-family: Garamond, Baskerville, "Baskerville Old Face", "Hoefler Text", "Times New Roman", serif;`

```
Eurostile-BoldExtendedTwo
Eurostile-ExtendedTwo
Garamond-BoldCondensed
Garamond-BoldCondensedItalic
Garamond-BookCondensed
Garamond-BookCondensedItalic
Garamond-UltraCondensed
```

**Torchbearer**

```
BlackmoorPlain
Souvenir-Demi
Souvenir-Light
Souvenir-Medium
Souvenir-MediumItalic
WoodtypeOrnaments-One
```

**D&D3.4**

```
Bookmania-Bold
Bookmania-Regular
MrsEavesAllSmallCaps
MrsEavesSmallCaps
ScalaSansOffc
ScalaSansOffc-Bold
ScalaSansScOffc
```

**Pathfinder**

```
TreacherousCurves Regular Font
Nexus Serif Regular Italic
```

**Comment by petrosh** [comment]
# Jovian Despair

- [Jovian-Despair.pdf](https://github.com/petrosh/diarissues/files/935834/Jovian-Despair.pdf)

**Comment by petrosh** [comment]
# Ideas

- [Silo serie, comic](http://comicdownload.net/search/Jet-City-Graphics)
- [The Poor Man’s Conlang](http://www.gnomestew.com/game-mastering/tools-for-gms/the-poor-mans-conlang/)  
  - [Number of syllables](http://stackoverflow.com/questions/5686483/how-to-compute-number-of-syllables-in-a-word-in-javascript)
- [Idle RPGs](http://www.gnomestew.com/game-mastering/tools-for-gms/idle-rpgs-and-tabletop-game-time/)  
  > Idle games are games that more or less play themselves with minimal intervention from the player.
- [Grant Howitt Microgames](https://drive.google.com/drive/folders/0B_U6IBmtxcz1WmxKdndMalI0Ymc)
- With `edit-in-place` or `content-editable` and jquery you edit like **Observable**
  - https://beta.observablehq.com/d/e74e841d22b6fd4b
  - `<div contenteditable="true">This text can be edited by the user.</div>`
- **Editor in `modal`. Insert too in `modal`**
- Ship crew wake up, memory loss, seek out his role. And his skills.

## Words

- Flight of fancy
- Begging bowl
- Crying wolf

## Launch versioning

- https://semver.org/

- Power on
  - 13:30 Vehicle is powered on
- Propellant load  
  - 3:50 Commence loading liquid oxygen (LOX)
  - 3:40 Commence loading RP-1 (rocket grade kerosene)
  - 3:15 LOX and RP-1 loading complete
- Internal power
- Autosequence start  
  - 0:06 Falcon 9 terminal count autosequence started
- Go for launch  
  - 0:02 SpaceX Launch Director verifies go for launch
  - 0:02 Range Control Officer (USAF) verifies range is go for launch
  - 0:01 Command flight computer to begin final prelaunch checks. Turn on pad deck and Niagara water
- Startup
- 0:00:40 Pressurize propellant tanks
- Ignition sequence  
  - 0:00:03 Engine controller commands engine ignition sequence to start
- 0:00 Falcon 9 liftoff

---

- 0:00:40 Stage one propulsion nominal
- 0:01 Max Q (moment of peak mechanical stress on the rocket)
- 0:03 1st stage engine shutdown/main engine cutoff (MECO)
- 0:03 1st and 2nd stages separation
- 0:03 2nd stage engine start
- 0:04 Fairing separation
- 0:08 2nd stage engine cutoff-1 (SECO-1)
- 0:27 2nd stage engine restart
- 0:28 2nd stage engine cutoff-2 (SECO-2)
- 0:33 SES-8 satellite deployed

---

### Paz
- 01:13:00 SpaceX Launch Director verifies go for propellant load
- 01:10:00 RP-1 (rocket grade kerosene) loading underway
- 00:35:00 LOX (liquid oxygen) loading underway
- 00:07:00 Falcon 9 begins engine chill prior to launch
- 00:01:00 Flight computer commanded to begin final prelaunch checks
- 00:01:00 Propellant tank pressurization to flight pressure begins
- 00:00:45 SpaceX Launch Director verifies go for launch
- 00:00:03 Engine controller commands engine ignition sequence to start
- 00:00:00 Falcon 9 liftoff

## Expanse

- Factions
- Missions
- Events feed

> S05 prepare for boarding

## Timeline

`repository_nwo`

- Created
- Commits
- Comments

## Star Trek TOS Uniforms

**Colors**
- Command & Helm: Gold
- Operations, Engineering & Security: Red
- Science & Medical: Blue

**Stripes**
- Captains: Solid Dotted Solid (Kirk)
- Commanders: Solid Solid (Spock)
- Lieutenant Commanders: Solid Dotted (Scott, McCoy)
- Lieutenants: Solid (Uhura, Sulu)
- Ensigns: None (Chekov)

# Dawn of Everything

[new republic](https://newrepublic.com/article/163941/dawn-everything-book-review-earliest-societies-anarchists)

Standard Version of History (40,000­–12,000 B.C.E.)

**Social forms**
- bands, mobile groups of a few families
- tribes, of perhaps 100 members, moving a few times a year
- chiefdoms (region or people ruled by a chief), hundreds strong, centered in one place but with smaller groups occasionally moving away for various reasons
- states, with thousands of members, centered in cities, and with a central government more or (usually) less accountable to the populace.

**Mode of subsistence**
- hunting/gathering
- gardening/foraging/herding
- farming
- industry

**Political forms**
- egalitarianism
- private property
- kingship (often just ceremonial)
- bureaucratic state

| Social | Subsistence | Politic |
|---|---|---|
| Band | hunters/gathers | egalitarian |
| Tribe | garden/forage/herd | private property |
| Chiefdom | farm | kingship |
| State | Industry | Bureaucracy |

**Comment by petrosh** [comment]
## Angry Planet

**Map**

```yml
- map:
  type: 2d
  image_url: https://...
  name: Milky Way
  systems:
    -
      name: Sol
      location: [126,48]
  regions:
    -
      name: Orion Arm
      path:
        - x: 26
          y: 45
```

**Timeline**

- Day 33, GC Standard 261
  Galactic Commons Membership Hearings, public record 3223—3433-3
- Day 128, GC Standard 306
  TRANSIT
- Day 129, GC Standard 306
  A COMPLAINT
- Day 130, GC Standard 306
  ARRIVAL
- Day 130, GC Standard 306
  TIP OFF
- Day 130, GC Standard 306
  THE TUNNELERS
- Day 130, GC Standard 306
  TECHNICAL DETAILS
- Day 131, GC Standard 306
  BLIND PUNCH
- Day 132 - 145, GC Standard 306
  THE JOB
- Day 163, GC Standard 306
  PORT CORIOL
- Day 180, GC Standard 306
  THE WANE
- Day 245, GC Standard 306
 INTRO TO HARMAGIAN COLONIAL HISTORY
- Day 249, GC Standard 306
  CRICKET
- Day 251, GC Standard 306
  THE LAST WAR
- Day 335, GC Standard 306
  KEDRIUM
- Day 397, GC Standard 306
  HATCH, FEATHER, HOUSE
- Day 45, GC Standard 307
  OCTOBER 25
- Day 121, GC Standard 307
  HERESY
- Day 157, GC Standard 307
  HEDRA KA
- Day 157, GC Standard 307
  SEVEN HOURS
- Day 158, GC Standard 307
  HARD RESET
- Day 158, GC Standard 307
  STAYING, LEAVING
- Day 169, GC Standard 307
  THE COMMITTEE
- Day 214, GC Standard 307
  ALL SAID AND DONE

**Comment by petrosh** [comment]
# Dawn_of_Worlds

- [`DoW` Dawn_of_Worlds](http://www.clanwebsite.org/games/rpg/Dawn_of_Worlds_game_1_0Final.pdf)

**Rounds**
Every player take a turn in a round.

- Add 2d6 `PP` Power Points to your total
- Take actions (optional)
- Earn a cumulative 1 PP each turn you saved 5 PPs or less. First turn 1 PP, second consecutive turn 2 PP, three or more consecutive turns 3PP.

**Ages (minimun 5 rounds)**
One particular aspect of world creation.

- `Age 1` Geography: 1 round ≈ 500 years
- `Age 2` Races: 1 round ≈ 100 years
- `Age 3` Relations (Politics, War, Learning): 1 round ≈ few years, adjustable

**Actions**
Spend points on your turn for one or more actions.

**Table of Powers**

|Power |1st Age - Land |2nd Age - Races |3rd Age - Relations|
|--|--|--|--|
|Shape Land, 1" |3 | 5 | 8 |
|Shape Climate, 1" |2 | 4 | 6 |
|Create Race |22 | 6 | 15 |
|Create Subrace |12 | 4 | 10 |
|Command Race** |8 | 4 | 3 |
|Command City** |6 | 4 | 2 |
|Advance Civilization |10 | 5 | 6 |
|Advance City |8 | 4 | 5 |
|Purify Civ. +1 Align *| 5 | 3 | 4 |
|Corrupt Civ. -1 Align *| 4 | 3 | 3 |
|Purify City, +1 Align *| 4 | 3 | 3 |
|Corrupt City, -1 Align *| 3 | 2 | 2 |
|Event| 10 | 7 | 9 |
|Create Order| 8 | 6 | 4 |
|Command Order |4 | 3 | 2 |
|Create Avatar| 10 | 7 | 8 |
|Command Avatar |2 | 1 | 1 |
|Catastrophe, 1"| 10 |10 | 10 |

- _* Only once per target per turn._
- _**Player must have either an Avatar, or order(sect) present where directions are given._

**Conflicts**

- Roll 2d6+bonus (technology, terrain, weather)  
  For multiple armies roll for each one, survivors continue at -1 for each battle.

**Comment by petrosh** [comment]
# Traveller

- [Sectors]
- [Worlds]
- [Jump]
- [Cutter]

## Sectors

> Sector: Mapping unit in astrography equal to 16 subsectors. Average density 500 to 650 worlds per sector. Sectors are named, and several synonyms are in common use, including march (or marches), region, reach (or reaches), quad- rant, and matrix. The Spinward Marches, for example, is a sector.
As a rough means of comparing size, the sector counts of the large interstellar states and areas of settlement are: the Imperium 27, the Aslan Hierate 18, the Hive Federation 17, the Two Thousand Worlds 14, the Vargr Extents 14, the Zhodani Consulate 13, and the Solomani Confederation 11.

- **Regina** subsector  
  one of 16 subsectors in the Spinward Marches sector.
- **Regina** is the sector capital  
  the region is a hub for trade with the Vargr to coreward and the Zhodani to spinward.
- Planetary Locations:  
  - **Dentus** (Spinward Marches/Regina)

<details><summary>Maps</summary>

![schermata 2017-09-25 alle 18 36 10](https://user-images.githubusercontent.com/4997583/30819853-6ff4822c-a220-11e7-9bf3-be06e102d74a.png)

![schermata 2017-09-25 alle 18 41 24](https://user-images.githubusercontent.com/4997583/30820089-2e472ff4-a221-11e7-8305-90cf4481b879.png)

</details>

**Subsector Data**

- The Regina subsector contains 32 worlds with a total population of 60.1 billion. The highest population is 26 billion, at Rethe; the highest tech level is D, at Efate, Uakye, Pixie, Boughene, and Yori. All worlds in the Regina subsector are members of the lmperium with the exception of Ruie.

- The column headed name gives the name of the world. The four digit number under location is the hex number of the world on the subsector hex grid. UPP is universal planetary profile. Codes under bases indicate naval and scout bases; A indicates both a naval and a scout base; B indicates both a naval base and a scout way station. A t the far right margin, G indicates that the system has one or more gas giants; A indicates that the world is an amber travel zone; R indicates that the world is a red travel zone.

- The heavy lines connecting several worlds are express boat routes providing communications between worlds of the Imperium. These routes are also common trade and transport routes with regular commercial transportation provided by one or more transport megacorporations. Service to locations not on these routes is less frequent and less dependable.

```yml
subsector:
  -
    name: Regina
    location: 0310
    UPP: A788899 A
    Bases: A
    Remarks: Rich. Subsector Capital.
    Gas Giants: G
```

**Subsector names**

The sixteen subsectors (with capitals listed in parentheses) in the Spinward marches are:
- A Chronor (Chronor)
- B Jewell (Jewell)
- C Regina (Regina)
- D Aramis (Aramis)
- E Querion (Querion)
- F Vilis (Frenzie)
- G Lanth (Lanth)
- H Rhylanor (Rhylanor)
- I Darrian (Mire)
- J the Sword Worlds (Gram)
- K Lunion (Lunion)
- L Mora (Mora)
- M the Five Sisters (Iderati)
- N District 268 (Mertactor)
- 0 Glisten (Glisten)
- P Trin's Veil (Trin).

<details><summary>Image</summary>

![schermata 2017-09-25 alle 18 53 22](https://user-images.githubusercontent.com/4997583/30820653-d6942cce-a222-11e7-9981-8aeeb7216ca6.png)
</details>

# Worlds

**World Type**

**Universal World Profile**

|Name|Hex|Physical Stats|Base Code|Trade Classifications|Extended Stats|Allegiance Code
|:--|:--|:--|:--|:--|:--|:--|
|Roup|0407|C77A9A9-6|S|Hi In Wa|A323|Im|

<details><summary>Image</summary>

![schermata 2017-09-25 alle 18 58 26](https://user-images.githubusercontent.com/4997583/30820877-997d4c70-a223-11e7-8de4-52c82517173f.png)
</details>

# Ships

**USDF** Universal Ship Description Format

- [TL] TL 9
- [Descriptive Name] Cutter
- [Ship Hull Displacement]-ton 50-ton
  - ([Hull Damage Value] Hull, [Structure Damage Value] Structure,) (1 Hull, 1 Structure)
- [General Description of Ship's Function] designed to take a sealed 30-ton module from surface to orbit
- [Jump Drive Code]
- [Maneuver Drive Code] sK
- [Power Plant Code] sK
- Jump-[Jump Number]
- [Thrust Number]-G 4-G
- [Fuel Tonnage] tons 1.3 tons
- [Weeks of Power] one
- [Number of Jumps]
- jump-[Jump Number]
- [Any additional fuel usage notes]
- [Computer Number / bis or fib options noted] 1
- [Sensors Type] Standard
- ([Sensors DM].) -4
- [Number of Staterooms] 1+1
- [Number of Low Berths]
- [Number of Hardpoints] one
- [Fire Control Tonnage] one
- [Describe number and type of turrets, weapon systems, missiles and sandcasters ammunition]
- [Number of Screens Installed]
  - [Number and type of screens]
- [Number of Small Craft Hangars]
  - [Number and contents of each hangar]
- [Cargo Tonnage] 1.3
- [Hull Configuration] Standard
- [Armor Type] ([Armor Rating] points.)
  - [Note any Ship's Armor options that have been installed.]
- [Additional components, fuel processors, fuel scoops] 30-ton module berth
- [Crew Total]: [List crew positions] one: Pilot
- [Double the Number of Non-Crew Staterooms] 1
- [Cost of Ship] 24.305
- [Construction Time] 32 weeks

## Jump

JD are rated from 1 to 6: the number of parsecs which can be travelled in one week.

## Cutter

**METHODS OF MODULE USE**

- Cargo Bays/Spacedocks
- Vehicle Bays
- External Lashings
- Modular Couplings
- Intrinsic Couplings
- External Grapples

**Modules TL10**

- Cargo
  - Bulk Cargo
  - Cargo
  - Containerized Cargo
- Vehicular
  - Fighter Pod `10-ton`
  - Garage `3,500 cf`
  - Tugboat Cutter `2,687.5 t`
  - Small Craft Bay `2x10 dtons`
  - Vehicle Transport `12 dtons`
- Transport
  - Commuter `260`
  - Passenger`48 for 24h`
  - Quarters `5-10`
  - High-Capacity Berthing `20-80`
  - Low Berth `176`
  - Luxury Passenger Transport `2`
  - Luxury Quarters `1-2`
  - Standard Commercial `48/32 10 dtons`
- Entertainment
  - Recreation `100`
  - Theater `100`
  - Traveling Stage
  - Safari `12`
- Scientific
  - Survey `3`
  - Laboratory `3-6`
  - Scout Survey Base `10`
  - Scout Support Base `4`
  - Planetary Infrastructure `7`
- Military
  - Prison Transport `normal, brig, cryotube`
  - High-Capacity Troop-Berthing `12-48`
  - Troop Transport `48`
  - Marine Command
  - Customs
- Emergency
  - Medevac `36+36+36=108`
  - Medical `3`
  - Firefighting
- Industrial
  - Mining Pallet
  - Fuel Skimmer `16 m/h`
  - Xboat Relay `2`
- Support
  - Search and Rescue
  - Recovery `1`
  - Logistics `4`
  - Portable Field Shop `3-6`
- Station
  - Class I Starport
  - Command
  - Commercial
  - Communications `6`
  - Engineering `4+4`
  - Hydroponics `400`
  - Industrial
  - Traffic Control `16`

**Cepheus**

- Logistic
  1. Cargo `29`
  1. Fuel `28.5`
  1. Vehicular `23`
- Transport
  1. Commuter `18`
  1. Low Berth `58`
  1. Prison `14`
  1. Luxury `7`
  1. Laboratory `7`

```yml
-
   Module Type: Cargo
   Cost (MCr): 1.5
   Notes: Cargo (29 tons), 1 airlock
-
   Module Type: Commuter
   Cost (MCr): 2.5
   Notes: Cabin (18 people), 1 airlock, 1 small fresher/kitchenette
-
   Module Type: Fuel
   Cost (MCr): 1.25
   Notes: Fuel tankage (28.5 tons), Fuel processors (1.5 tons)
-
   Module Type: Laboratory
   Cost (MCr): 8
   Notes: Laboratory (7 scientists), 2 airlocks
-
   Module Type: Low Berth Transport
   Cost (MCr): 4
   Notes: 58 low berths, 1 airlock
-
   Module Type: Luxury Suites
   Cost (MCr): 4.5
   Notes: 7 staterooms, 2 airlocks
-
   Module Type: Prison Transport
   Cost (MCr): 4.5
   Notes: 14 detention cells, 1 airlock
-
   Module Type: Vehicular Transport
   Cost (MCr): 6.75
   Notes: Hangar (23 tons of vehicles), allows repairs/maintenance
```

- Transport (Cargo, Passengers)
- Security (Military, Emergency)
- Infrastructure (Industrial, Communications)
- Scientific (Scout, Laboratory)
- Stations

**Comment by petrosh** [comment]
# Schemas

Schema Gist https://gist.github.com/petrosh/6fc2fde4b3f91bd8ace59364174d3064

**Examples**

- https://github.com/tool-of-lore/jekyll-any-theme
- https://github.com/fork-n-play/cuddly-fiesta
- https://github.com/petrosh/try-jekyll-any-theme

**Attributes**

Booleans

- **`readonly`** user cannot modify the value of the control, good for *watching* fields like `id`s or `"template": "{{fname}} {{lname}}"`
- **`required`** validated at submit

**Include**

File name in `/_includes`

- **`include` and `include_below`** to render search results or some modal to enter persisting keys

**Type**

- `text`
- `textarea`: `markdownify`
- `number`: does not respond to letters key, used like `if $(input).data 'numeric' then value = Number value`
- `checkbox`: need a `value` to return and a `<label>`, a group has same `name`, can have a `checked` empty attribute, multiple example `interest=coding&interest=music`
- `radio`: need a `value` to return and a `<label>`, a group has same `name`, can have a `checked` empty attribute
- `range`: usually has validation with others inputs like not exceeding some field
- `date`: usually for an `event` can be with `datepicker` or for another calendar
- `time`: well keyboard driven
- `color`: should have a SVG and an `id` or `name` like `upper_color`
- `url`: has weak native validation like `http:x` is good

**Content editable**

Like https://beta.observablehq.com/d/e74e841d22b6fd4b  
`- contenteditable: true`

```html
<div contenteditable="true">
  This text can be edited by the user.
</div>
```

**Pools**

- `pool`: Refer to a pool setted (e.g. 100) that the sum of referring fields must not exceed
  **Disadvantages** recommended limit -40
  **Quirks** up to five
- `money`: You start with money equal to the campaign starting wealth, modified by your personal wealth level

```yml
# GURPS character
pools:
  - character_points: 100 # max limit of the sum of every pooled property
  - disadvantages_points: -40 # min limit of the sum
attributes:
  strength:
    value:
      pool: character_points # or
      pools: [ character_points ]
      roll: 3d6
      # race mod defined in races?
disadvantages:
  type: array
  pools:
    - disadvantages_points
    - character_points
```

**References**

- `ref`: Refer tables, lists or colony descriptor's mod to attribute

```yml
pools:
  character_points:
    ref: races.character_points
```

```yml
planets:
  jupiter:
    orbiting: sol
    type: Gas giant
    moons:
      ref: moons.jovian_moons
```

**Arrays**

```yml
type: schema
id: character
properties:
  name:
    [type: text]
    description: ...
  threats:
    array:
      - Zorgon the Conqueror
      - The Hive Armada
      - Rogue Captain
  owns:
    array:
      - Laser
      - Radio
      - Water
    multiple: 2
  problems:
    array:
      - title: Fuel hog
        description: Always needs energy crystals
      - title: One Medical pod
        description: Captain Darcy is in it
  moons:
    ref: moons
    filter:
      orbiting: "Jupiter"
  quirks:
    ref: gurps.character.quirks
    multiple: 5
  pets:
    ref: pets
```

**Blog posts schema**

```yml
# Landing page
type: "//rec"
required:
  sticky_post:
    type: "tag:blogpost"
  other_posts:
    type: "//arr"
    contents: "tag:blogpost"
# Blog post
uri: tag:blogpost
schema:
  type: "//rec"
  required:
    title: "//str"
    body: "//str"
    draft: "//bool"
  optional:
    subtitle: "//str"
    tags:
      type: "//arr"
      contents: "//str"
```

---

- [ ] Commit or Pull, admin or forks, `auth` level for input fields
