### ISSUE TITLE
practice

### ISSUE THREAD

**Issue by petrosh** [petrosh/diarissues#2]
## David Robson
- [David Robson on Ashtanga Yoga & Floating](https://www.youtube.com/watch?v=9IuUDtANH68)
- [Everywhere you look you see God](http://www.elephantjournal.com/2011/12/my-sadhana-is-taking-over-my-life--david-robson/)
## [Vinyasa Yoga Teacher Training with Michel Besnard](https://www.youtube.com/watch?v=iJ76cR5cLlA)
- Feel the event, live _in_ the moment, and then move on.
- You do your practice every day and then it is finished.
- Enjoy the ride.
## [Iyengar teaching 'Ashtanga' 1977](https://www.youtube.com/watch?v=SgEC9uxFDQo&t=0m45s)
- Speedy Iyengar jumping into the asymmetrical arm balance Astavakrasana

---

Ardha Baddha Padmottanasana = half-bound-Lotus-intense-stretch

``` css
.pl-cm { color: #999988; font-style: italic; }
.pl-cp { color: #999999; font-weight: bold; }
.pl-c1 { color: #999988; font-style: italic; }
.pl-cs { color: #999999; font-weight: bold; font-style: italic; }
.pl-gd { color: #000000; background-color: #ffdddd; }
.pl-gd .x { color: #000000; background-color: #ffaaaa; }
```
