### ISSUE TITLE
Worlds

### ISSUE THREAD

**Issue by petrosh** [petrosh/diarissues#20]
- [Postantera](https://github.com/petrosh/diarissues/issues/20#issuecomment-324926867)
- [Flogoria](https://github.com/petrosh/diarissues/issues/20#issuecomment-324926977)
- [Jovian Despair](https://github.com/petrosh/diarissues/issues/19#issuecomment-295419883)
- [Ages of Urthe](https://github.com/petrosh/diarissues/issues/20#issuecomment-324933824)
- [Angry Planet](https://github.com/petrosh/diarissues/issues/19#issuecomment-331936259)
- [Silo serie](https://github.com/petrosh/diarissues/issues/19#issuecomment-331936518)
- [Traveller](https://github.com/petrosh/diarissues/issues/19#issuecomment-331939124)
- [One Page](https://github.com/petrosh/diarissues/issues/20#issuecomment-332193279)
- [The Witch Is Dead](https://github.com/petrosh/diarissues/issues/20#issuecomment-365073647)
- [Savage Worlds sci-fi worldbuilder](https://github.com/petrosh/diarissues/issues/20#issuecomment-365751905)
- [Series](https://github.com/petrosh/diarissues/issues/20#issuecomment-406242883)  `expanse` `discovery`
- [The Freeze-Frame Revolution](https://github.com/petrosh/diarissues/issues/20#issuecomment-427431524)

**Comment by petrosh** [comment]
# Postantera

- https://www.reddit.com/r/worldbuilding/search?q=Worldbuilding+Monthly&sort=new&restrict_sr=on
- https://github.com/Postantera

**Comment by petrosh** [comment]
# Flogoria

- https://www.reddit.com/r/Flogoria/
- https://github.com/Flogoria

**Front matter v1**

```yml
name: Ancient Rock Sculpture
object: monument
material: stone
location: Flogorian Plains
near:
  - name: Statue
    distance: 900
    direction: east
image: https://i.redd.it/etns7a7berhz.jpg
description: https://www.reddit.com/r/Flogoria/comments/6vu9jz/ancient_rock_sculpture_on_the_flogorian_plains/dm30lcw/
tagged:
  - turist
  - hound
  - effigy
  - smelly
  - perplexing
  - staue
```

**JSON Data**

- http://petrosh.it/domtools/reddizza/#https://www.reddit.com/r/Flogoria/comments/6vu9jz/ancient_rock_sculpture_on_the_flogorian_plains/
- http://petrosh.it/domtools/reddizza/#https://www.reddit.com/r/Flogoria/comments/6lgo2b/flogorian_badlands_6wd_tours/

**Post**

`response[0].data.children[0].data`

```json
{
  title: "Flogorian Badlands 6WD Tours",
  url: "https://i.redd.it/3nobof7c1u7z.jpg",
  subreddit_name_prefixed: "r/Flogoria",
  created: 1499314751,
  author: "uglyink",
  permalink: "/r/Flogoria/comments/6lgo2b/flogorian_badlands_6wd_tours/",
  thumbnail: "https://b.thumbs.redditmedia.com/jB3QOOvcIQqmb5lN7MBt_PFHYrXq77mgj15hpcqPb4Y.jpg",
  score: 47
}
```

**Comment**

`response[1].data.children[0].data`

```json
{
  body_html: "&lt;div class="md"&gt;&lt;p&gt; ... @ugly_ink&lt;/p&gt;↵&lt;/div&gt;",
  author: "uglyink",
  score: 7
}
```

**Comment by petrosh** [comment]
# Ages of Urthe

- [The Ribbon of Space: a schematic illustration of an 11-dimensional fantasy universe](http://imgur.com/6l0eGP8)

<details><summary>Map</summary>

![ptuir0t](https://user-images.githubusercontent.com/4997583/29717877-24d9b58c-89b1-11e7-8337-518338cab30b.jpg)

</details>

## Space

**3 Dimensions for the Ribbon**

| Scale | Level | Color |
|:--|:--|:--|
| Largest | Top | Blue |
| Middle | Middle | Yellow |
| Smallest | Bottom | Red |

## Planes

| Plane | Defined by Dimension x | Axis x | Defined by Dimension y | Axis y |
|:--|:--|:--|:--|:--|
| **Spiritual** | Moral | Good / Evil | Philosophical | Law / Chaos |
| **Physical** | Temporal | Past / Future | Vital |Positive / Negative |
| **Elemental** | Thermal | Hot / Cold | Integral | Tight / Loose |

**Transitional Planes**

| Plane | Type | Traversed in Dimension | Axis |
|:--|:--|:--|:--|
| **Astral** | Supergalactic | Mental | Finite / Infinite |
| **Ethereal** | Subatomic | Primal | Matter / Energy |

**Comment by petrosh** [comment]
# One Page

- **(System) Sheet RPG** - A generic fantasy RPG where the character sheet is the rulebook 
 [imgur](https://imgur.com/varp2ba) - [png](https://i.imgur.com/varp2ba.png)
- **Edge of the Galaxy** - A one-page RPG about a sci-fi journey, based on Fall of Magic  
  [imgur](https://imgur.com/bm0iZiv) - [png](https://i.imgur.com/bm0iZiv.png)
- **Laser & Feelings** - A quick-play roleplaying game, based on the songs of The Doubleclicks.   
  [pdf](http://onesevendesign.com/lasers_and_feelings_rpg.pdf)
- **Ill-Gotten Realms** - Long cons and larceny in a Fantasy Land.  
  [jpg](https://archive.is/swfPP/4b75b2c1716d90e77c625f54720a0cfcfc5d7810)
- **Honey Heist** - You are a goddamn Bear
  [pdf](https://www.dropbox.com/s/v9o6wqwegdhty1p/honey-heist-rules.pdf)

**Comment by petrosh** [comment]
# The Witch Is Dead

<details><summary>B&W</summary>

![schermata 2018-02-12 alle 22 28 30](https://user-images.githubusercontent.com/4997583/36120690-478714ac-1044-11e8-91ab-6e9f4405e805.png)

</details>


```yml
# Village: roll twice
village:
  - Filled
  - Religious
# Hunter: roll
hunter:
  - Drunk
# Twist: roll secret
twist:
  - The hunter didn't do it
# Roll: d10 + relevant trait (0-3)
challenge_rating:
  - 6 # trivial (simple)
  - 7 # easy (basic)
  - 8 # medium (challenging)
  - 9 # hard (difficult)
  - 10 # deadly (near_impossible)
# Woodland animal traits
clever:
  - Interact and understand humans
fierce:
  - Scare, bite, scratch
sly:
  - Sneak, steal, hide
quick:
  - Outpace, climb, evade
# Roll a d10 to see what you are
- fox
- cat
- toad
- spider
- owl
- hare
- magpie
- crow
- dog
- rat
# Roll a d10 for your spell
- unseen_hand
- conjure_light
- speack_human
- lock_open
- conjure_dinner
- make_flame
- tidy_clean
- plant_growth
- distract_confuse
- book_aloud
```
